org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.121
neo_version_range=[21.1.0,)
loader_version_range=[4,)
mod_id=mob_farm_block
mod_name=Mob Farm Block
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.akitaattribute.mobfarmblock
jei_version=19.25.1.332
